### ISSUE TITLE
2.0 migration (meta issue)

### ISSUE THREAD

**Issue by danielmewes** [rethinkdb/horizon#704]
Horizon 2.0 changes the metadata format.
- [x] `hz migrate` to migrate existing Horizon metadata in a RethinkDB server #705
- [x] `hz schema save` and `hz schema apply` should switch to a new structured format to specify indexes in the schema.toml files #706
- [x] `hz schema apply` needs to detect old index definitions and interpret them, so that users can still import existing schema files #707
- [x] The Horizon server should detect existing Horizon metadata in RethinkDB and error out, suggesting migration (`hz migrate`) #708
- [x] Documentation https://github.com/rethinkdb/horizon-docs/issues/104
