### ISSUE TITLE
`hz migrate` for 2.0

### ISSUE THREAD

**Issue by danielmewes** [rethinkdb/horizon#705]
Add a new command `hz migrate` to the CLI, that connects to an existing RethinkDB server (or starts one, depending on command line arguments), and then migrates the metadata in RethinkDB to the new 2.0 format (renaming indexes, deleting the internal DB at the end etc.).

When it's done, it should tell the user that it migrated the schema and suggest running `hz schema save` to save the new schema. Or alternatively, it can run `hz schema save` itself and print where it has saved the schema.
### Todos

(added by @deontologician):
- [x] Make a backup of the database
  - [x] Add an option to turn this off
- [x] Move tables from `${project}_internal.foo` to `${project}.hz_foo`
  - [x] Don't add the `hz_` prefix to the `users` table
- [x] Rename all indices from the previous format to the json format
- [x] Fix the `hz_table` format from `{ id: collectionName,  table: tableName }` to `{ id: collectionName, table_id: tableId }`
- [x] Rename tables to match the collection name
- [x] Export the schema
  - [ ] Add an option to turn this off

**Comment by deontologician** [comment]
This is like 90% done. The other 90% is fixing bugs and testing it, which I should finish up tomorrow
